CREATE TABLE USUARIO_PROFESSOR (
  IdUsuario INTEGER NOT NULL,
  Email VARCHAR(100) NOT NULL UNIQUE,
  Senha VARCHAR(100) NOT NULL,
  TipoUsuario VARCHAR(20),
  IdProfessor INTEGER NOT NULL,
  Nome VARCHAR(255) NOT NULL,
  PRIMARY KEY (IdUsuario, IdProfessor)
);

CREATE TABLE DISCIPLINA (
  IdDisciplina INTEGER PRIMARY KEY,
  NomeDisciplina VARCHAR(200) NOT NULL,
  Codigo VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE CURSO (
  IdCurso INTEGER PRIMARY KEY,
  NomeCurso VARCHAR(255) NOT NULL
);

CREATE TABLE PERIODO (
  IdPeriodo INTEGER PRIMARY KEY,
  NumeroPeriodo INTEGER NOT NULL,
  FK_CURSO_IdCurso INTEGER NOT NULL
);

CREATE TABLE HORARIO (
  IdHorario INTEGER PRIMARY KEY,
  DiaSemana VARCHAR(50) NOT NULL,
  Turno VARCHAR(20) NOT NULL,
  HoraInicio TIME NOT NULL,
  HoraFim TIME NOT NULL
);

CREATE TABLE SEMESTRE_LETIVO (
  IdSemestre INTEGER PRIMARY KEY,
  Ano INTEGER NOT NULL,
  Semestre INTEGER NOT NULL,
  UNIQUE (Ano, Semestre)
);

CREATE TABLE SALA (
  IdSala INTEGER PRIMARY KEY,
  NumeroSala VARCHAR(20) NOT NULL,
  Capacidade INTEGER,
  FK_PREDIO_IdPredio INTEGER NOT NULL
);

CREATE TABLE PREDIO (
  IdPredio INTEGER PRIMARY KEY,
  NomePredio VARCHAR(100) NOT NULL
);

CREATE TABLE ALOCACAO (
  IdAlocacao INTEGER PRIMARY KEY,
  FK_USUARIO_PROFESSOR_IdUsuario INTEGER NOT NULL,
  FK_USUARIO_PROFESSOR_IdProfessor INTEGER NOT NULL,
  FK_DISCIPLINA_IdDisciplina INTEGER NOT NULL,
  FK_SEMESTRE_LETIVO_IdSemestre INTEGER NOT NULL,
  FK_HORARIO_IdHorario INTEGER NOT NULL,
  FK_SALA_IdSala INTEGER NOT NULL
);

CREATE TABLE PODE_MINISTRAR (
  FK_USUARIO_PROFESSOR_IdUsuario INTEGER NOT NULL,
  FK_USUARIO_PROFESSOR_IdProfessor INTEGER NOT NULL,
  FK_DISCIPLINA_IdDisciplina INTEGER NOT NULL,
  PRIMARY KEY (
    FK_USUARIO_PROFESSOR_IdUsuario,
    FK_USUARIO_PROFESSOR_IdProfessor,
    FK_DISCIPLINA_IdDisciplina
  )
);

CREATE TABLE OFERECE_EM (
  FK_PERIODO_IdPeriodo INTEGER NOT NULL,
  FK_DISCIPLINA_IdDisciplina INTEGER NOT NULL,
  PRIMARY KEY (FK_PERIODO_IdPeriodo, FK_DISCIPLINA_IdDisciplina)
);

ALTER TABLE PERIODO
  ADD CONSTRAINT FK_PERIODO_CURSO
  FOREIGN KEY (FK_CURSO_IdCurso)
  REFERENCES CURSO (IdCurso)
  ON DELETE RESTRICT;

ALTER TABLE SALA
  ADD CONSTRAINT FK_SALA_PREDIO
  FOREIGN KEY (FK_PREDIO_IdPredio)
  REFERENCES PREDIO (IdPredio)
  ON DELETE RESTRICT;

ALTER TABLE ALOCACAO
  ADD CONSTRAINT FK_ALOCACAO_USUPROF
  FOREIGN KEY (
    FK_USUARIO_PROFESSOR_IdUsuario,
    FK_USUARIO_PROFESSOR_IdProfessor
  )
  REFERENCES USUARIO_PROFESSOR (IdUsuario, IdProfessor);

ALTER TABLE ALOCACAO
  ADD CONSTRAINT FK_ALOCACAO_DISC
  FOREIGN KEY (FK_DISCIPLINA_IdDisciplina)
  REFERENCES DISCIPLINA (IdDisciplina);

ALTER TABLE ALOCACAO
  ADD CONSTRAINT FK_ALOCACAO_SEM
  FOREIGN KEY (FK_SEMESTRE_LETIVO_IdSemestre)
  REFERENCES SEMESTRE_LETIVO (IdSemestre);

ALTER TABLE ALOCACAO
  ADD CONSTRAINT FK_ALOCACAO_HOR
  FOREIGN KEY (FK_HORARIO_IdHorario)
  REFERENCES HORARIO (IdHorario);

ALTER TABLE ALOCACAO
  ADD CONSTRAINT FK_ALOCACAO_SALA
  FOREIGN KEY (FK_SALA_IdSala)
  REFERENCES SALA (IdSala);

ALTER TABLE PODE_MINISTRAR
  ADD CONSTRAINT FK_PODEMIN_USUPROF
  FOREIGN KEY (
    FK_USUARIO_PROFESSOR_IdUsuario,
    FK_USUARIO_PROFESSOR_IdProfessor
  )
  REFERENCES USUARIO_PROFESSOR (IdUsuario, IdProfessor)
  ON DELETE RESTRICT;

ALTER TABLE PODE_MINISTRAR
  ADD CONSTRAINT FK_PODEMIN_DISC
  FOREIGN KEY (FK_DISCIPLINA_IdDisciplina)
  REFERENCES DISCIPLINA (IdDisciplina)
  ON DELETE RESTRICT;

ALTER TABLE OFERECE_EM
  ADD CONSTRAINT FK_OFEREM_PERIODO
  FOREIGN KEY (FK_PERIODO_IdPeriodo)
  REFERENCES PERIODO (IdPeriodo)
  ON DELETE RESTRICT;

ALTER TABLE OFERECE_EM
  ADD CONSTRAINT FK_OFEREM_DISC
  FOREIGN KEY (FK_DISCIPLINA_IdDisciplina)
  REFERENCES DISCIPLINA (IdDisciplina)
  ON DELETE RESTRICT;
